### PR TITLE
Feature: multiple measurements per query

### LINKED ISSUE #9: Support for selecting from multiple measurements
Influx now supports selecting from multiple measurements:

```influx-ql
select * from "msmt_1", "msmt_2"
```

### PR DESCRIPTION
**Pull request by yura415**
Closes #9

### CODE REVIEW

**Comment by vicanso** [comment]
@yuricodes  I want your modification to be backwards compatible. You can add `addMeasurement` function, but not to remove the measure setter function. I suggest you to modify it like this:

```js
set measurement(measurement) {
  console.warn("the measurement setter function will be deprecated");
  internal(this).measurements = [measurement];
}
get measurement() {
  console.warn("the measurement getter function will be deprecated");
  return internal(this).measurements[0];
}
```

But the way, please don't change the original test for current version.

**Comment by yura415** [comment]
So I need to revert to using `.measurement = 'http'` in the original tests?

**Comment by vicanso** [comment]
Yes, because single measurement is used more often.I have thought about this again and I suggest  not to add the deprecated warning.

```js
set measurement(measurement) {
  internal(this).measurements = [measurement];
}
get measurement() {
  return internal(this).measurements[0];
}
```

**Comment by yura415** [comment]
Ok. Done

**Pull request merged**
